### ISSUE TITLE
Замечания от 19.05.2017

### ISSUE THREAD

**Issue by QuickNickKoenig** [coyul/AnimalsLoader#1]
MainActivity: 
-   private static int LOADER_ID = 1; // пропущен квалификатор final
- При загрузке ProgressBar скрывается. Почему? Потому что ты скрываешь RelativeLayout, в котором он находится.

Animal:
- С префиксом m должно быть поле, не параметр в конструкторе. m не должно включаться в getter-ы и setter-ы.
- Форматирование.

AnimalGenerator:
- Форматирование.
- Метод, возвращающий список животных, должен называться provideAnimals(), он же называется provideAnimal().
- Выбор рандомного животного лучше писать именно в генераторе.

AnimalLoader:
- Форматирование.
- Random инициализировать следует в конструкторе.

**Comment by coyul** [comment]
- Все исправлено, кроме форматирования в классах Animal и AnimalLoader (все хорошо)
- Во время загрузки виден только progress bar
- Логика AnimalLoader и AnimalGenerator изменилась: сначала получаем в AnimalLoader список (вдруг он изменился), потом получаем по списку и своему randomу случайное животное.
